{
gROOT->Reset();
gSystem->AddIncludePath("-I/$CMSSW_BASE/src/");
gSystem->Load("$CMSSW_BASE/lib/slc4_ia32_gcc345/libtestEventFilterSiStripRawToDigi.so");
gSystem->CompileMacro("ObjectFilter.cc","fkg","libObjectFilter");
gSystem->CompileMacro("SiStripPerformancePlots.cc","fkg","libSiStripPerformancePlots");
gSystem->CompileMacro("SiStripPerformanceAnalysis.cc","fkg","libSiStripPerformanceAnalysis");
gSystem->CompileMacro("SiStripPerformanceFigures.cc","fkg","libSiStripPerformanceFigures");
}
